import "server-only";

import { randomUUID } from "crypto";
import { google } from "googleapis";
import { getGoogleEnv } from "@/lib/env";

export const SERVICE_REPORT_WORKBOOK_ID = "1QuNstJwL2wxBgM-bwa83r8rU9PZNln3tmih6DOBG2oY";
export const SERVICE_REPORT_WORKBOOK_URL = `https://docs.google.com/spreadsheets/d/${SERVICE_REPORT_WORKBOOK_ID}/edit`;

export const ACTIVITY_HEADERS = [
  "Event ID", "Logged At", "Date", "Service", "Category", "Action",
  "Actor", "Summary", "Record ID", "Status",
];

let cachedSheets: ReturnType<typeof google.sheets> | null = null;
const verifiedTabs = new Set<string>();

function sheetsClient() {
  if (cachedSheets) return cachedSheets;
  const env = getGoogleEnv();
  const auth = new google.auth.JWT({
    email: env.serviceAccountEmail,
    key: env.privateKey,
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
  });
  cachedSheets = google.sheets({ version: "v4", auth });
  return cachedSheets;
}

function escapeTitle(title: string) {
  return `'${title.replace(/'/g, "''")}'`;
}

async function appendRow(title: string, headers: string[], row: unknown[]) {
  if (row.length !== headers.length) throw new Error(`${title} row does not match its configured columns.`);
  const sheets = sheetsClient();
  const sheet = escapeTitle(title);
  if (!verifiedTabs.has(title)) {
    const headerResult = await sheets.spreadsheets.values.get({
      spreadsheetId: SERVICE_REPORT_WORKBOOK_ID,
      range: `${sheet}!1:1`,
    });
    const current = (headerResult.data.values?.[0] || []).map((value) => String(value).trim());
    if (headers.some((header, index) => current[index] !== header)) {
      throw new Error(`The "${title}" tab is missing or has incompatible columns.`);
    }
    verifiedTabs.add(title);
  }
  await sheets.spreadsheets.values.append({
    spreadsheetId: SERVICE_REPORT_WORKBOOK_ID,
    range: `${sheet}!A:ZZ`,
    valueInputOption: "USER_ENTERED",
    insertDataOption: "INSERT_ROWS",
    requestBody: { values: [row] },
  });
}

export async function appendCategorizedReport(input: {
  tab: string;
  headers: string[];
  row: unknown[];
  date: string;
  service: string;
  category: string;
  actor: string;
  summary: string;
}) {
  const recordId = randomUUID();
  const loggedAt = new Date().toISOString();
  await appendRow(input.tab, input.headers, [recordId, ...input.row, loggedAt]);
  await appendRow("Activity Log", ACTIVITY_HEADERS, [
    randomUUID(), loggedAt, input.date, input.service, input.category,
    "Saved", input.actor, input.summary, recordId, "Success",
  ]);
  return recordId;
}

export async function appendGeneratedDocumentLog(input: {
  date: string;
  service: string;
  url: string;
  actor?: string;
}) {
  const recordId = randomUUID();
  const loggedAt = new Date().toISOString();
  const headers = ["Record ID", "Date", "Service", "Document URL", "Status", "Generated By", "Generated At"];
  await appendRow("Generated Documents", headers, [
    recordId, input.date, input.service, input.url, "Ready", input.actor || "Service Manager", loggedAt,
  ]);
  await appendRow("Activity Log", ACTIVITY_HEADERS, [
    randomUUID(), loggedAt, input.date, input.service, "Document",
    "Generated", input.actor || "Service Manager", "Detailed service document generated", recordId, "Success",
  ]);
  return { recordId, workbookUrl: SERVICE_REPORT_WORKBOOK_URL };
}

export async function appendEmailDeliveryLog(input: {
  date: string;
  service: string;
  recipient: string;
  reportType: "summary" | "full";
  subject: string;
  providerMessageId: string;
  documentUrl?: string;
}) {
  const recordId = randomUUID();
  const loggedAt = new Date().toISOString();
  const headers = [
    "Message ID", "Sent At", "Date", "Service", "Recipient", "Report Type",
    "Subject", "Brevo Message ID", "Status", "Document URL",
  ];
  await appendRow("Email Log", headers, [
    recordId, loggedAt, input.date, input.service, input.recipient,
    input.reportType === "full" ? "Full report" : "Summary",
    input.subject, input.providerMessageId, "Sent", input.documentUrl || "",
  ]);
  await appendRow("Activity Log", ACTIVITY_HEADERS, [
    randomUUID(), loggedAt, input.date, input.service, "Email",
    "Sent", input.recipient, `${input.reportType === "full" ? "Full report" : "Summary"} emailed`, recordId, "Success",
  ]);
  return recordId;
}
