"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, Loader2, RefreshCcw, ShieldCheck, Trash2, UserRoundCog } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { CustomSelect } from "@/components/ui/custom-select";

type Role = "general_user" | "service_manager" | "hod" | "admin" | "super_admin";
type RoleRow = { email: string; role: Role; department: string | null; isActive: boolean; updatedAt: string };
type Assignment = { id: string; serviceDate: string; service: string; managerEmail: string; accessStartsAt: string; accessEndsAt: string; status: string };
const roleLabels: Record<Role, string> = { general_user: "General User", service_manager: "Service Manager", hod: "HOD", admin: "Admin", super_admin: "Super Admin" };
const roleOptions = Object.entries(roleLabels).map(([value, label]) => ({ value, label }));

export function RoleManager() {
  const [roles, setRoles] = useState<RoleRow[]>([]); const [assignments, setAssignments] = useState<Assignment[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [email, setEmail] = useState(""); const [role, setRole] = useState<Role>("general_user"); const [department, setDepartment] = useState("");
  const [serviceDate, setServiceDate] = useState(""); const [service, setService] = useState(""); const [managerEmail, setManagerEmail] = useState("");
  const [starts, setStarts] = useState(""); const [ends, setEnds] = useState("");
  const managers = useMemo(() => roles.filter((item) => item.role === "service_manager" && item.isActive), [roles]);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/admin/roles", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setRoles(data.roles); setAssignments(data.assignments); } catch (error) { toast.error((error as Error).message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  async function send(method: "POST" | "DELETE", body: Record<string, unknown>, message: string) { setSaving(true); try { const response = await fetch("/api/admin/roles", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); toast.success(message); await load(); } catch (error) { toast.error((error as Error).message); } finally { setSaving(false); } }
  function saveRole(event: FormEvent) { event.preventDefault(); void send("POST", { kind: "role", email, role, department }, "Access rights saved."); }
  function saveAssignment(event: FormEvent) { event.preventDefault(); void send("POST", { kind: "assignment", serviceDate, service, managerEmail, accessStartsAt: new Date(starts).toISOString(), accessEndsAt: new Date(ends).toISOString() }, "Sunday posting linked to access rights."); }

  return <div className="space-y-6">
    <section className="overflow-hidden rounded-[2rem] bg-[linear-gradient(125deg,#07152f,#24315f_52%,#146079)] p-6 text-white shadow-xl sm:p-8"><div className="flex items-center justify-between gap-5"><div><h2 className="text-2xl font-bold tracking-tight sm:text-3xl">Role manager</h2><p className="mt-2 max-w-2xl text-sm text-white/65">Control permanent roles and link Sunday postings to temporary Service Manager access. Access begins and expires with each assignment window.</p></div><ShieldCheck className="h-9 w-9 shrink-0 text-cyan-300" /></div></section>
    <div className="grid gap-6 lg:grid-cols-2">
      <Card variant="glass"><CardHeader><CardTitle>Assign a role</CardTitle><CardDescription>Department is required for HOD visibility and optional for other roles.</CardDescription></CardHeader><CardContent><form onSubmit={saveRole} className="space-y-4"><div><Label htmlFor="role-email">Member email</Label><Input id="role-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div><Label>Role</Label><CustomSelect value={role} onChange={(value) => setRole(value as Role)} options={roleOptions} /></div><div><Label htmlFor="role-department">Department</Label><Input id="role-department" value={department} onChange={(e) => setDepartment(e.target.value)} placeholder="e.g. Main auditorium" /></div><Button variant="gradient" disabled={saving}><UserRoundCog className="mr-2 h-4 w-4" />Save access rights</Button></form></CardContent></Card>
      <Card variant="glass"><CardHeader><CardTitle>Schedule Service Manager access</CardTitle><CardDescription>The selected manager can work only on this service during the access window.</CardDescription></CardHeader><CardContent><form onSubmit={saveAssignment} className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="service-date">Sunday date</Label><Input id="service-date" type="date" value={serviceDate} onChange={(e) => setServiceDate(e.target.value)} required /></div><div><Label htmlFor="service-name">Service</Label><Input id="service-name" value={service} onChange={(e) => setService(e.target.value)} placeholder="1st Service" required /></div><div className="sm:col-span-2"><Label>Service Manager</Label><CustomSelect value={managerEmail} onChange={setManagerEmail} options={managers.map((item) => ({ value: item.email, label: item.email }))} placeholder="Select a Service Manager" /></div><div><Label htmlFor="access-start">Access starts</Label><Input id="access-start" type="datetime-local" value={starts} onChange={(e) => setStarts(e.target.value)} required /></div><div><Label htmlFor="access-end">Access ends</Label><Input id="access-end" type="datetime-local" value={ends} onChange={(e) => setEnds(e.target.value)} required /></div><Button className="sm:col-span-2" variant="gradient" disabled={saving || !managerEmail}><CalendarClock className="mr-2 h-4 w-4" />Link posting and access</Button></form></CardContent></Card>
    </div>
    <Card variant="glass"><CardHeader className="gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>People and access</CardTitle><CardDescription>{roles.length} configured user{roles.length === 1 ? "" : "s"}</CardDescription></div><Button size="sm" variant="outline" onClick={load} disabled={loading}><RefreshCcw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</Button></CardHeader><CardContent>{loading ? <div className="grid min-h-32 place-items-center"><Loader2 className="h-6 w-6 animate-spin" /></div> : <div className="divide-y divide-border/60">{roles.map((item) => <div key={item.email} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{item.email}</p><p className="text-sm text-muted-foreground">{item.department || "All departments"}</p></div><div className="flex items-center gap-2"><Badge>{roleLabels[item.role]}</Badge><Button size="icon" variant="ghost" aria-label={`Remove ${item.email}`} disabled={item.role === "super_admin" || saving} onClick={() => send("DELETE", { kind: "role", email: item.email }, "Role removed.")}><Trash2 className="h-4 w-4" /></Button></div></div>)}</div>}</CardContent></Card>
    <Card variant="glass"><CardHeader><CardTitle>Scheduled access</CardTitle><CardDescription>Sunday assignments are the source of temporary Service Manager permissions.</CardDescription></CardHeader><CardContent><div className="divide-y divide-border/60">{assignments.length ? assignments.map((item) => <div key={item.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{item.service} · {item.serviceDate}</p><p className="text-sm text-muted-foreground">{item.managerEmail} · expires {new Date(item.accessEndsAt).toLocaleString("en-NG")}</p></div><div className="flex items-center gap-2"><Badge variant="outline">{item.status}</Badge><Button size="icon" variant="ghost" aria-label={`Remove ${item.service} assignment`} onClick={() => send("DELETE", { kind: "assignment", id: item.id }, "Assignment removed.")}><Trash2 className="h-4 w-4" /></Button></div></div>) : <p className="py-8 text-center text-sm text-muted-foreground">No Sunday access has been scheduled yet.</p>}</div></CardContent></Card>
  </div>;
}
